### ISSUE TITLE
ActiveRecord::RecordNotFound

### ISSUE THREAD

**Issue by calebsylvest** [calebsylvest/pro#1]
I've built two methods for joining a Project using the Devise auth system. A Project can either be Free or Cost money, payments work with Stripe and are setup for dev testing. 

The `free` method works just fine (in the `charge_controller.rb`) but the `pay` method does not. They both use the same `project` stuff (still new to Rails and don't know what all these thingz are called) but when a user tries to join and buy a Project they run into the error below (see attached image).

File referenced in error:
https://github.com/calebsylvest/pro/blob/master/app/controllers/charge_controller.rb#L13

![screen shot 2015-06-06 at 9 40 34 pm](https://cloud.githubusercontent.com/assets/4457883/8022408/37a41630-0c95-11e5-98b8-f2ae6f343a24.png)

Sorry, don't have a dev version, only local.

Rails version 4.2.1

**Comment by stevehanson** [comment]
Just posted on Twitter, but I think the issue is that the params (`project_id`, `stripeToken`, `stripeEmail`) aren't being sent from the form. The offending lines are [these three](https://github.com/calebsylvest/pro/blob/master/app/views/project/show.html.erb#L25-L27), because they are missing the `=` in the opening tag and are therefore not output on the page.

**Comment by calebsylvest** [comment]
Thanks @stevehanson!
